on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: qt libs
        uses: tlambert03/setup-qt-libs@v1        
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Publish Quarto using headless-display
        uses: aganders3/headless-gui@v2
        # adapted from quarto-dev/quarto-actions/publish@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUARTO_PRINT_STACK: true
        with:
          run: |
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
            quarto publish gh-pages . --no-browser